version: '3.8'

services:
  bankshield-system:
    build: ./bankshield-system
    ports:
      - "8000:8000"
    volumes:
      - ./bankshield-system:/app
    environment:
      - FASTAPI_ENV=production
    restart: always

  bankshield-client:
    build: 
      context: ./bankshield-client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: always
