services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: discorre
      POSTGRES_PASSWORD: 0412
      POSTGRES_DB: bankshield
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U discorre1 -d bankshield"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bankshield-network

    
  bankshield-system:
    build: ./bankshield-system
    ports:
      - "8000:8000"
    volumes:
      - ./bankshield-system:/app
    environment:
      - FASTAPI_ENV=production
      - DATABASE_URL=postgresql://discorre:0412@db:5432/bankshield
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bankshield-network
    restart: always

  bankshield-client:
    build: 
      context: ./bankshield-client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - bankshield-network
    restart: always

volumes:
  postgres_data:

networks:
  bankshield-network:
    driver: bridge
