# Dockerfile.tests
FROM python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["pytest", "test_app.py", ">>", "logs.txt"]