name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: discorre
          POSTGRES_PASSWORD: 0412
          POSTGRES_DB: bankshield
        ports:
          - 35432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: bankshield-system
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start services
        run: docker compose -f docker-compose.yml up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until docker exec $(docker ps -qf "name=db") pg_isready -U discorre; do
            sleep 2
          done

      - name: Run tests inside backend container
        run: |
          docker exec $(docker ps -qf "name=bankshield-system") pytest test_app.py
